name: "action tempo-cli release"
description: ""

permissions:
  contents: write
  discussions: write

inputs:
  shell:
    description: "Shell to use for steps"
    required: false
    default: "cmd"
    # add setup-tempo-cli version input
    # add required github token input
    # optionally add the nexus mods api key

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup tempo-cli
      uses: Tempo-Organization/setup-tempo-cli@main

    - name: Run tempo-cli mod release creation command
      shell: ${{ inputs.shell }}
      run: tempo_cli run full_run_all --settings_json ".tempo.json"

    - name: List all releases
      shell: ${{ inputs.shell }}
      run: dir "%CD%\Modding\releases\*.zip" /b /a-d 2>nul > release_list.txt

    - name: Temporary body.md creation
      shell: cmd
      run: echo temporary placeholder > body.md

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: "body.md"
        tag_name: test
        files: |
          Modding/releases/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}



# then print the contents of current_dir/.tempo.json

# have a step here that checks the json file mods info, to get mod names, mod version, description, etc...

# have a step here that makes a release for each using the information above

# add mod version
# add mod description
# add way to increment specific mod versions through commitizen logic
